apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:latest
        ports:
        - containerPort: 9000
        env:
        - name: SONAR_ES_BOOTSTRAP_CHECKS_DISABLE
          value: "true"

---

apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonar-ingress
spec:
  ingressClassName: istio
  rules:
    - host: ${{ secrets.HOST }}
      http:
        paths:
        - backend:
            service:
              name: sonarqube
              port:
                number: 80
          path: /
          pathType: Prefix
  tls:
    - hosts:
      - ${{ secrets.HOST }}
      secretName: kyma-gateway-certs
