name: TradeTix CD Pipeline

on:
#   workflow_run:
#     workflows:
#       - "TradeTix CI Pipeline"
#     types:
#       - "completed"
#     branches:
#         - "main"
    push:
        branches:
        - main

jobs:
    push-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              
            - name: Log in to the Container registry
              uses: docker/login-action@v3.1.0
              with:
                registry: ${{ secrets.REGISTRY }}
                username: ${{ secrets.REGISTRY_USERNAME }}
                password: ${{ secrets.REGISTRY_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5.3.0
              with:
                context: .
                push: true
                tags: latest

