name: TradeTix CD Pipeline

on:
#   workflow_run:
#     workflows:
#       - "TradeTix CI Pipeline"
#     types:
#       - "completed"
#     branches:
#         - "main"
    push:
        branches:
        - main

jobs:
    push-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              
            - name: Build the Docker image
              run: docker build -t ${{ secrets.REGISTRY }}/tradetix:latest -f k8s/Dockerfile .

            - name: Docker run the image
              run: docker run -p 3001:3001 ${{ secrets.REGISTRY }}/tradetix:latest

            - name: Log in to the Container registry
              uses: docker/login-action@v3.1.0
              with:
                registry: ${{ secrets.REGISTRY }}
                username: ${{ secrets.REGISTRY_USERNAME }}
                password: ${{ secrets.REGISTRY_PASSWORD }}

            - name: Push the Docker image
              run: docker push ${{ secrets.REGISTRY }}/tradetix:latest

