name: K8s Deployment


on:
    workflow_run:
        workflows:
            - "TradeTix CD Pipeline"
        types:
            - "completed"
        branches:
            - "main"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup kubectl
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 -d > ${HOME}/.kube/config
          cat ${HOME}/.kube/config

      - name: Setup context
        run: |
          kubectl config set-context --current --namespace=prod
          kubectl get pods