name: K8s Deployment


on:
  workflow_run:
    workflows:
    - "TradeTix CD Pipeline"
    types:
    - "completed"
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
    - run: kubectl get pods