name: Staging

on:
  push:
    branches:
      - 'main'
      - 'canary'
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
    inputs: 
      releaseTo:
        description: 'Release to a specific environment'
        required: false
        default: 'dev'
        options:
        - 'canary'
        - 'prod'

jobs:
  push_to_registry:
    name: Staging
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: pravinkumar08654/tradetix


      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./k8s/Dockerfile
          push: true
          tags: pravinkumar08654/tradetix:dev
          labels: ${{ steps.meta.outputs.labels }}

      - name: Workflow Webhook Action
        uses: distributhor/workflow-webhook@v3.0.7
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          data: '{ "message": "Image pushed to Docker Hub", "tag": "dev"}'


  canary:
    if: github.event.inputs.releaseTo == 'canary'
    name: Publish to Canary
    needs: [push_to_registry]

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: pravinkumar08654/tradetix

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./k8s/Dockerfile
          push: true
          tags: pravinkumar08654/tradetix:canary
          labels: ${{ steps.meta.outputs.labels }}

      - name: Workflow Webhook Action
        uses: distributhor/workflow-webhook@v3.0.7
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          data: '{ "message": "Image pushed to Docker Hub with Canary Tag", "tag": "canary" }'

  prod:
    if: github.event.inputs.releaseTo == 'prod'
    name: Publish to Prod
    needs: [push_to_registry]

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: pravinkumar08654/tradetix

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./k8s/Dockerfile
          push: true
          tags: pravinkumar08654/tradetix:prod
          labels: ${{ steps.meta.outputs.labels }}

      - name: Workflow Webhook Action
        uses: distributhor/workflow-webhook@v3.0.7
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          data: '{ "message": "Image pushed to Docker Hub with Prod Tag", "tag": "prod" }'


            
      